# Generated by Django 4.2.4 on 2023-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='users/profile_photo', verbose_name='Фото профиля'),
        ),
    ]
