# Generated by Django 4.2.4 on 2023-09-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipment',
            field=models.CharField(default=1, max_length=25, verbose_name='Оборудование'),
            preserve_default=False,
        ),
    ]
