# Generated by Django 4.2.4 on 2023-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='equipment',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Оборудование'),
        ),
    ]
