# Generated by Django 4.2.4 on 2023-10-03 20:15

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='Укажите город проживания', max_length=25, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Телефон для контакта', max_length=31, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_photo', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_experience',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Опыт работы'),
        ),
    ]
