# Generated by Django 4.2.4 on 2023-10-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_about_me_alter_user_city_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='user',
            name='equipment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Оборудование'),
        ),
    ]
