# Generated by Django 4.2.4 on 2023-08-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=25, verbose_name='Название услуги')),
                ('image_service', models.ImageField(blank=True, upload_to='users/tags', verbose_name='Фотография услуги')),
                ('cost_service', models.PositiveIntegerField(verbose_name='Стоимость услуги')),
                ('description_service', models.TextField(max_length=25, verbose_name='Описание услуги')),
                ('due_date', models.DateTimeField(verbose_name='Срок выполнения')),
                ('equipment', models.CharField(max_length=25, verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
