# Generated by Django 4.2.4 on 2023-09-03 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='author',
        ),
        migrations.AddField(
            model_name='service',
            name='author',
            field=models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
