# Generated by Django 4.2.4 on 2023-09-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='author',
            field=models.ManyToManyField(related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='service',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='services', to='services.tag', verbose_name='Вид съемки'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.mediafile'),
        ),
        migrations.AddField(
            model_name='mediaservice',
            name='media_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_services', to='services.mediafile'),
        ),
        migrations.AddField(
            model_name='mediaservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_services', to='services.service'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediafiles', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddConstraint(
            model_name='mediafile',
            constraint=models.CheckConstraint(check=models.Q(('photo__exact', ''), ('link__exact', ''), _connector='OR'), name='Укажите только один вид медиа'),
        ),
    ]
