# Generated by Django 4.2.4 on 2023-09-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_services', to='services.mediafile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_services', to='services.service')),
            ],
        ),
    ]
