# Generated by Django 4.2.4 on 2023-09-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='service',
            name='min_duration',
        ),
    ]
