# Generated by Django 4.2.4 on 2023-09-15 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='equipment',
        ),
        migrations.AddField(
            model_name='service',
            name='order_delivery_time',
            field=models.PositiveSmallIntegerField(default=1, help_text='введите срок предоставленияобработаных фотографий в днях', validators=[django.core.validators.MinValueValidator(1, 'минимальное значение 1')], verbose_name='Срок выполнения'),
            preserve_default=False,
        ),
    ]
