# Generated by Django 4.2.4 on 2023-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_mediafile_photo_alter_mediafile_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='media_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('PHOTO', 'Photo')], max_length=25, verbose_name='Тип медиа файла'),
        ),
    ]
