# Generated by Django 4.2.4 on 2023-10-03 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало выполнения'),
        ),
    ]
