# Generated by Django 4.2.4 on 2023-11-21 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0007_alter_service_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='author',
        ),
        migrations.AddField(
            model_name='service',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
