# Generated by Django 4.2.4 on 2023-12-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='received',
            field=models.BooleanField(default=False, verbose_name='Статус прочитано'),
        ),
    ]
