# Generated by Django 4.2.4 on 2023-09-25 19:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chat',
        ),
    ]
