# Generated by Django 4.2.4 on 2023-08-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback_property',
            options={'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната в недвижимости', 'verbose_name_plural': 'Комнаты в недвижимости'},
        ),
    ]
