# Generated by Django 4.2.4 on 2023-10-24 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальное значение 1'), django.core.validators.MaxValueValidator(limit_value=5, message='Максимальное значение 5')])),
                ('description', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
