# Generated by Django 4.2.4 on 2023-10-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_date_review_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-post_date']},
        ),
    ]
