# Generated by Django 4.2.4 on 2023-11-03 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0007_alter_service_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название заказа')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость заказа')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата заказа')),
                ('completion_date', models.DateTimeField(verbose_name='Время исполнения')),
                ('status', models.BooleanField(default=False, verbose_name='Статус выполнения заказа')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='chat.chat', verbose_name='Чат')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service', verbose_name='Услуга в заказе')),
                ('users', models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Участники сделки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка исполнителя')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raitings', to='orders.order', verbose_name='')),
                ('user', models.ManyToManyField(related_name='raitings', to=settings.AUTH_USER_MODEL, verbose_name='Участники рейтинга')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ('order',),
            },
        ),
    ]
