# Generated by Django 4.2.4 on 2023-09-25 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_room_chat_rename_room_message_chat'),
        ('services', '0004_alter_service_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='order',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='chat.chat', verbose_name='Чат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service', verbose_name='Услуга в заказе'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='users',
            field=models.ManyToManyField(related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Участники сделки'),
        ),
        migrations.AddField(
            model_name='raiting',
            name='user',
            field=models.ManyToManyField(related_name='raitings', to=settings.AUTH_USER_MODEL, verbose_name='Участники рейтинга'),
        ),
    ]
