# Generated by Django 4.2.4 on 2023-11-19 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='users',
        ),
        migrations.RemoveField(
            model_name='raiting',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='executor_user',
            field=models.ForeignKey(default=1993, on_delete=django.db.models.deletion.CASCADE, related_name='executor_orders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель заказа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raiting',
            name='customer_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='customer_raitings', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='raiting',
            name='executor_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='executor_raitings', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raiting',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raitings', to='orders.order', verbose_name='Название заказа'),
        ),
    ]
