# Generated by Django 4.2.4 on 2023-08-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('author',), 'verbose_name': 'Сообoение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
