# Generated by Django 4.2.4 on 2023-08-26 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_message_author'),
        ('orders', '0003_alter_message_options'),
    ]

    operations = [
    ]
