# Generated by Django 4.2.4 on 2023-08-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_merge_20230826_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('author',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='orders.chat'),
            preserve_default=False,
        ),
    ]
